file_paths:
  candidate_file: "./data/candidate_data-gap-solutions-only.csv"
  listings_file: "./data/t04_itid.csv"
  output_dir: "./output"

hugging_face:
  model_id: "C:\\Users\\Sam.Nazari\\.cache\\huggingface\\hub\\models--sentence-transformers--all-MiniLM-L6-v2\\snapshots\\fa97f6e7cb1a59073dff9e6b13e2715cf7475ac9"
  hf_token: "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"
  use_local: true
# C:\Users\Sam.Nazari\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2\snapshots\8b3219a92973c328a8e22fadcfa821b5dc75636a
# C:\Users\Sam.Nazari\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2\snapshots\fa97f6e7cb1a59073dff9e6b13e2715cf7475ac9
# C:\\Users\\Sam.Nazari\\.cache\\huggingface\\hub\\models--microsoft--phi-2\\snapshots\\ef382358ec9e382308935a992d908de099b64c23
#"C:\\Users\\Sam.Nazari\\.cache\\huggingface\\hub\\models--sentence-transformers--all-MiniLM-L6-v2\\snapshots\\8b3219a92973c328a8e22fadcfa821b5dc75636a"#"C:\\Users\\Sam.Nazari\\.cache\\huggingface\\hub\\models--sentence-transformers--all-mpnet-base-v2\\snapshots\\9a3225965996d404b775526de6dbfe85d3368642" #"sentence-transformers/all-MiniLM-L12-v2" #"sentence-transformers/all-MiniLM-L6-v2" #sentence-transformers/all-MiniLM-L12-v2
# C:\Users\Sam.Nazari\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2\snapshots\9a3225965996d404b775526de6dbfe85d3368642

llm:
  model_id: "C:\\Users\\Sam.Nazari\\.cache\\huggingface\\hub\\models--sentence-transformers--all-MiniLM-L6-v2\\snapshots\\fa97f6e7cb1a59073dff9e6b13e2715cf7475ac9" #"C:\\Users\\Sam.Nazari\\.cache\\huggingface\\hub\\models--sentence-transformers--all-MiniLM-L6-v2\\snapshots\\8b3219a92973c328a8e22fadcfa821b5dc75636a" #"meta-llama/Llama-3.3-70B-Instruct"
  api_token: "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"
  use_local: true

debug_mode: true